; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;env:uirb-v02 without UIRBcorelib
;RAM:   [====      ]  40.1% (used 821 bytes from 2048 bytes)
;Flash: [======    ]  55.4% (used 17932 bytes from 32384 bytes)
;
;env:uirb-v02 with UIRBcorelib
;RAM:   [====      ]  44.8% (used 917 bytes from 2048 bytes)
;Flash: [========  ]  80.0% (used 25900 bytes from 32384 bytes)
;

[platformio]
name = GirsUIRB                  ; Name of the project, shown in PlatformIO
description = AGirs firmware adapted for the Universal IR Blaster (UIRB)
default_envs = uirb-v02                      ; Default environment for building and uploading firmware

[configuration]
default_baud_rate = 38400
option_1_baud = 9600
option_2_baud = 19200
option_3_baud = 250000
low_bat_notify_period_seconds = 15

; Common settings shared across all environments
[env]
platform = atmelavr                          ; Specifies the Atmel AVR platform (used for ATmega microcontrollers)
framework = arduino                          ; Utilizes the Arduino framework for development
lib_deps = 
    https://github.com/DjordjeMandic/UIRBcorelib.git#dev       ; UIRBcore library for Universal IR Blaster (GitHub: https://github.com/DjordjeMandic/UIRBcorelib)
    bengtmartensson/AGirs @ ^1.0.5
monitor_speed = ${configuration.default_baud_rate}                      ; Serial monitor baud rate (1M)
monitor_filters = default, time, colorize    ; Serial monitor: default output, timestamps, and colorized text
build_flags = 
    -I config.h
    -D SERIALBAUD=${configuration.default_baud_rate}
    -D OPTION_1_BAUD=${configuration.option_1_baud}
    -D OPTION_2_BAUD=${configuration.option_2_baud}
    -D OPTION_3_BAUD=${configuration.option_3_baud}
    -D LOW_BAT_NOTIFY_PERIOD_SECONDS=${configuration.low_bat_notify_period_seconds}

; Default environment for the UIRB V0.2 board with urboot bootloader
[env:uirb-v02]
board = uirb-v02-atmega328p                  ; Board configuration for UIRB V0.2 hardware (ATmega328P).
                                             ; Configuration details are defined in ./boards/uirb-v02-atmega328p.json.
build_type = release                         ; Specifies release build type
; upload_speed = 57600                       ; Uncomment if bootloader has issues with the default upload speed
; upload_port = COM6                         ; Uncomment and set this to specify a fixed upload port.
                                             ; Ports are automatically detected using hardware IDs (hwids).
                                             ; This is optional unless debugging with avr-stub, where it must be manually set.
                                             ; See issue: https://github.com/platformio/platform-atmelavr/issues/253
extra_scripts = 
    ./scripts/pio/backup_eeprom.py           ; Custom script to handle EEPROM backup operations:
                                             ; - Adds the `backupeep` target for backing up EEPROM data.
                                             ; - Adds the `archiveeep` target for archiving EEPROM backups to a ZIP file.
                                             ; - Adds the `cleaneep` target for removing empty EEPROM backup directories.

; Environment for the UIRB V0.2 board using USBasp as the programmer
[env:uirb-v02-usbasp]
extends = env:uirb-v02                       ; Inherit settings from the default UIRB V0.2 environment
upload_protocol = usbasp                     ; Use USBasp for uploading firmware
upload_flags =                               ; Additional configuration for USBasp:
  -PUSB                                      ; Specify USB as the upload port
  -B8                                        ; Set SPI clock speed (divide by 8) for stable uploads

; Environment for the UIRB V0.2 board for debugging with default options
[env:uirb-v02-dbg]
extends = env:uirb-v02                       ; Inherit settings from the default UIRB V0.2 environment
build_type = debug                           ; Specify debug build type
debug_svd_path = ./svd/atmega328p.svd        ; Path to the SVD file for ATmega328P (used for debugging)
; build_unflags = -Os                        ; Uncomment to remove optimization from regular builds
; debug_build_flags = -O0                    ; Uncomment to remove optimization from debug builds

; Environment for the UIRB V0.2 board for simulation and debugging using SimAVR
[env:uirb-v02-dbg-simavr]
extends = env:uirb-v02-dbg                   ; Inherit settings from the debug environment
debug_tool = simavr                          ; Use SimAVR for hardware simulation and debugging
build_flags = 
    ${env:uirb-v02-dbg.build_flags}          ; Inherit build flags from the debug environment
    -DUIRB_EEPROM_BYPASS_DEBUG               ; UIRBcore: Enable EEPROM bypass mode (data stored in RAM)
    -DUIRB_EEPROM_RPROG_DEBUG=4990           ; UIRBcore: Set Rprog resistance to 4990 ohms for debugging

